
# 162 features, https://universaldependencies.org/u/feat/index.html
UD_FEATS = [
    'PronType=Art', 'PronType=Dem', 'PronType=Emp', 'PronType=Exc',
    'PronType=Ind', 'PronType=Int', 'PronType=Neg', 'PronType=Prs',
    'PronType=Rcp', 'PronType=Rel', 'PronType=Tot',
    'NumType=Card', 'NumType=Dist', 'NumType=Frac', 'NumType=Mult',
    'NumType=Ord', 'NumType=Range', 'NumType=Sets',
    'Poss=Yes', 'Reflex=Yes', 'Foreign=Yes', 'Abbr=Yes', 'Typo=Yes',
    'Gender=Com', 'Gender=Fem', 'Gender=Masc', 'Gender=Neut',
    'Animacy=Anim', 'Animacy=Hum', 'Animacy=Inan', 'Animacy=Nhum',
    'NounClass=Bantu1', 'NounClass=Bantu2', 'NounClass=Bantu3',
    'NounClass=Bantu4', 'NounClass=Bantu5', 'NounClass=Bantu6',
    'NounClass=Bantu7', 'NounClass=Bantu8', 'NounClass=Bantu9',
    'NounClass=Bantu10', 'NounClass=Bantu11', 'NounClass=Bantu12',
    'NounClass=Bantu13', 'NounClass=Bantu14', 'NounClass=Bantu15',
    'NounClass=Bantu16', 'NounClass=Bantu17', 'NounClass=Bantu18',
    'NounClass=Bantu19', 'NounClass=Bantu20',
    'Number=Coll', 'Number=Count', 'Number=Dual', 'Number=Grpa',
    'Number=Grpl', 'Number=Inv', 'Number=Pauc', 'Number=Plur', 'Number=Ptan',
    'Number=Sing', 'Number=Tri',
    'Case=Abl', 'Case=Add', 'Case=Ade', 'Case=All', 'Case=Del', 'Case=Ela',
    'Case=Ess', 'Case=Ill', 'Case=Ine', 'Case=Lat', 'Case=Loc', 'Case=Per',
    'Case=Sub', 'Case=Sup', 'Case=Ter', 'Case=Abe', 'Case=Ben', 'Case=Cau',
    'Case=Cmp', 'Case=Cns', 'Case=Com', 'Case=Dat', 'Case=Dis', 'Case=Equ',
    'Case=Gen', 'Case=Ins', 'Case=Par', 'Case=Tem', 'Case=Tra', 'Case=Voc',
    'Case=Abs', 'Case=Acc', 'Case=Erg', 'Case=Nom',
    'Definite=Com', 'Definite=Cons', 'Definite=Def', 'Definite=Ind',
    'Definite=Spec',
    'Degree=Abs', 'Degree=Cmp', 'Degree=Equ', 'Degree=Pos', 'Degree=Sup',
    'VerbForm=Conv', 'VerbForm=Fin', 'VerbForm=Gdv', 'VerbForm=Ger',
    'VerbForm=Inf', 'VerbForm=Part', 'VerbForm=Sup', 'VerbForm=Vnoun',
    'Mood=Adm', 'Mood=Cnd', 'Mood=Des', 'Mood=Imp', 'Mood=Ind', 'Mood=Jus',
    'Mood=Nec', 'Mood=Opt', 'Mood=Pot', 'Mood=Prp', 'Mood=Qot', 'Mood=Sub',
    'Tense=Fut', 'Tense=Imp', 'Tense=Past', 'Tense=Pqp', 'Tense=Pres',
    'Aspect=Hab', 'Aspect=Imp', 'Aspect=Iter', 'Aspect=Perf', 'Aspect=Prog',
    'Aspect=Prosp',
    'Voice=Act', 'Voice=Antip', 'Voice=Bfoc', 'Voice=Cau', 'Voice=Dir',
    'Voice=Inv', 'Voice=Lfoc', 'Voice=Mid', 'Voice=Pass', 'Voice=Rcp',
    'Evident=Fh', 'Evident=Nfh', 'Polarity=Neg', 'Polarity=Pos',
    'Person=0', 'Person=1', 'Person=2', 'Person=3', 'Person=4',
    'Polite=Elev', 'Polite=Form', 'Polite=Humb', 'Polite=Infm',
    'Clusivity=Ex', 'Clusivity=In'
]
